// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeUYt5IShnHit3uWrdprjHwMxO1Q820BE',
    appId: '1:1025134083398:web:98ee8518c09f6c2117f947',
    messagingSenderId: '1025134083398',
    projectId: 'notesappmarcel',
    authDomain: 'notesappmarcel.firebaseapp.com',
    storageBucket: 'notesappmarcel.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOd73U8dTYYVr-lOxZgF41EmDZYQFxJGM',
    appId: '1:1025134083398:android:74fdbbfe51e3e81f17f947',
    messagingSenderId: '1025134083398',
    projectId: 'notesappmarcel',
    storageBucket: 'notesappmarcel.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeUYt5IShnHit3uWrdprjHwMxO1Q820BE',
    appId: '1:1025134083398:web:cf5cf103dcc112f417f947',
    messagingSenderId: '1025134083398',
    projectId: 'notesappmarcel',
    authDomain: 'notesappmarcel.firebaseapp.com',
    storageBucket: 'notesappmarcel.appspot.com',
  );

}